apiVersion: apps/v1
kind: Deployment
metadata:
  name: tom-deployment
  labels:
    app: tomcat-app 
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tomcat-app
  template:
    metadata:
      labels:
       app: tomcat-app
    spec:
      containers:
      - name: tomcat-cont
        image: tomcat:8.0
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        ports:
        - containerPort: 8080