apiVersion: v1
kind: ReplicationController
metadata:
  name: my-rc
spec:
  replicas: 2
  selector:
    app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: my-jenkins
        image: jenkins
        ports:
        - containerPort: 8080


  