apiVersion: v1
kind: Service
metadata:
  name: tom-service
  labels:
    app: tomcat-app
spec:
  selector:
    app: tomcat-app
  type: NodePort
  ports:
  - nodePort: 31001
    port: 8080
    targetPort: 8080