---
apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
spec:
  containers:
  - name: myapp-container
    image: mamillapalli/tomven
---
apiVersion: v1
kind: Service
metadata:
  name: azure-pod
spec:
  ports:
  - port: 8080
  selector:
    app: myapp
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-pod
spec:
  type: LoadBalancer
  ports:
  - port: 8080
  selector:
    app: myapp
---