---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: simple-deploy
spec:
  replicas: 1
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: jenkins
spec:
  containers:
  - name: my-jenkins
    image: jenkins
    ports:
    - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
spec:
  type: LoadBalancer
  ports:
  - port: 8080
  selector:
    app: jenkins
