---
- hosts : all
  become: yes
  tasks : 
  - name : apache installation
    apt:
      name: apache2
      update_cache: yes
      state: present
    notify:
    - restart apache2
  - name: installing php
    package:
      name: "{[item]}"
      state: present
      loop:
        -php 
        -libapache2-mod-php 
        -php-mysql
    notify:
      -restart apache2

  handlers:
    - name: restart apache2
    service:
      package: apache2
      state: restarted