---
- name: update ubuntu packages & install tomcat8
  apt:
    name: tomcat8
    update_cache: yes
    state: present
- name: copy tomcat8 file
  template:
    src: tomcat8.j2
    dest: /etc/default/tomcat8
  notify:
    - restart tomcat8
- name: install additional tomcat packages
  apt:
    name: "{{ item }}"
    state: present
  loop: "{{ tomcat_additional_packages }}"
- name: copy tomcat users
  template:
    src: tomcat-users.xml.j2
    dest: /etc/tomcat8/tomcat-users.xml
  notify:
   - restart tomcat8
- name: Deploying Game Of Life
  get_url:
    url: https://github.com/venkatmamillapalli/golwar/raw/master/gameoflife.war
    dest: /var/lib/tomcat8/webapps/gameoflife.war
  notify:
    - restart tomcat8

